@Library("jenlib") _

withCcache() {
	wafDefaultPipeline(projects: ["halco"],
	                   moduleOptions: [modules: ["ppu-toolchain"]],
	                   container: [app: "dls-core"],
	                   configureInstallOptions: "--with-pybind --build-profile=ci",
	                   notificationChannel: "#dls-software")

	wafDefaultPipeline(projects: ["halco"],
	                   container: [app: "wafer"],
	                   notificationChannel: "#softies",
	                   configureInstallOptions: "--build-profile=ci")
}
