#!/usr/bin/env python

from waflib import Utils
from waflib.extras import symwaf2ic
from waflib.extras.gtest import summary
import os.path


def depends(ctx):
    ctx('pywrap')
    ctx('halco')


def options(opt):
    hopts = opt.add_option_group('pybind11')
    hopts.add_withoption('pybind', default=None,
                         help='Use pybind11-based bindings')

    opt.load('compiler_cxx')
    opt.load('gtest')
    opt.load('python')
    opt.load('pytest')


def configure(cfg):
    cfg.env.with_pybind = getattr(cfg.options, 'with_pybind', None)
    if cfg.env.with_pybind not in [True, False]:
        toplevel_path = symwaf2ic.get_toplevel_path()
        projects = set(str(os.path.relpath(p, toplevel_path))
                       for p in symwaf2ic.get_required_paths())
        is_hicann_dls = any(project in projects for project in [
                            'haldls', 'fisch'])
        is_hicann = 'halbe' in projects
        if is_hicann_dls and is_hicann:
            cfg.fatal(
                'cannot build python bindings of both HICANN/DLS at the same time\n'
                '(please specify --with-pybind / --without-pybind explicitly)'
            )
        cfg.env.with_pybind = not is_hicann
    cfg.msg(
        'Using pybind11-based python bindings',
        ['no', 'yes'][cfg.env.with_pybind])

    cfg.load('compiler_cxx')
    cfg.load('python')
    cfg.check_python_version()
    cfg.check_python_headers()
    cfg.load('pytest')

    if cfg.env.with_pybind:
        cfg.load('genpybind')

def build(bld):
    if bld.env.with_pybind:
        bld(
            target='pyhalco_common',
            source='../include/halco/common/common.h',
            genpybind_tags='common',
            features='genpybind cxx cxxshlib pyext',
            use=['halco_common', 'pyhalco_common_files'],
        )

        for hx_version in [3]:
            bld(
                target='pyhalco_hicann_dls_vx_v%s' % hx_version,
                source='../include/halco/hicann-dls/vx/v%s/pycoordinates.h' % hx_version,
                genpybind_tags=['hicann_dls_vx', 'hicann_dls_vx_v%s' % hx_version],
                features='genpybind cxx cxxshlib pyext',
                use=['halco_common', 'halco_hicann_dls_vx_v%s' % hx_version,
                     'pyhalco_common'],
            )

            bld(
                name='pyhalco_hicann_dls_vx_v%s_tests' % hx_version,
                tests='test/pyhalco_test_hicann_dls_vx_v%s.py' % hx_version,
                features='use pytest',
                use='pyhalco_hicann_dls_vx_v%s' % hx_version,
                install_path='${PREFIX}/bin',
                pythonpath=['test'],
                test_timeout=150,
            )

    else:
        bld(
            target='pyhalco_common',
            features='cxx cxxshlib pypp pyext',
            script='common/generate_common_coordinate.py',
            gen_defines='PYPLUSPLUS __STRICT_ANSI__',
            defines='PYBINDINGS',
            headers='../include/halco/common/common.h',
            use=['halco_common', 'BOOST4HALCO', 'BOOST4PYHALCO', 'PYHALCO', 'pywrap',
                 'pywrapstdvector', 'pycellparameters', 'pyhalco_common_files'],
            includes='.',
        )

        bld(
            target='pyhalco_hicann_v2',
            features='cxx cxxshlib pypp pyext',
            script='hicann/v2/generate_hicann_v2_coordinate.py',
            gen_defines='PYPLUSPLUS __STRICT_ANSI__ BOOST_PP_VARIADICS',
            # gccxml requires non-variadic implementation of boost::variant for python wrappers
            defines=['PYBINDINGS', 'BOOST_VARIANT_DO_NOT_USE_VARIADIC_TEMPLATES'],
            export_defines='BOOST_VARIANT_DO_NOT_USE_VARIADIC_TEMPLATES',
            headers='../include/halco/hicann/v2/coordinates.h',
            use=['pyhalco_common', 'halco_hicann_v2'],
            includes='.',
        )

        bld(
            name='pyhalco_hicann_v2_tests',
            tests='test/pyhalco_test_hicann_v2.py',
            features='use pytest',
            use='pyhalco_hicann_v2',
            install_path='${PREFIX}/bin',
            pythonpath=['test'],
            test_environ={'PYHALCO_API_CHECK': '1'},
        )

    bld(
        name='pyhalco_common_tests',
        tests='test/pyhalco_test_common.py',
        features='use pytest',
        use='pyhalco_common',
        install_path='${PREFIX}/bin',
        pythonpath=['test'],
    )

    # flat installation of all sources (and generated py{c,d}) into lib/
    bld(
        features='py',
        target='pyhalco_common_files',
        source=bld.path.ant_glob('**/pyhalco_*.py'),
        relative_trick=False,
    )

    bld(name="pyhalco_hicann_v2_tools",
        features="py use",
        source=bld.path.ant_glob('**/hicann/v2/tools/*.py'),
        install_from="hicann/v2/tools",
        install_path="${PREFIX}/bin",
        chmod = Utils.O755,
        use="pyhalco_hicann_v2")

    bld.add_post_fun(summary)
